# Generated by Django 5.0.2 on 2024-12-12 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
